### PR TITLE
Upgrade to Latest version of SDK 3.1.0

### PR DESCRIPTION
**Pull request by MadCoderme**

### CODE REVIEW

**Review by MKrupauskas — APPROVED** [review]

**Comment by RinorDreshaj** [comment]
is this working with version 3.1

**Comment by MadCoderme** [comment]
I am already using with the updated version and ir works fine. But the only issue that happens is, Screen share doesn't work.

**Comment by deepakverma4** [comment]
@MadCoderme are you able to use latest SDK in ios too?
I'm facing issue because of ios sdk name changes

**Comment by MadCoderme** [comment]
Unfortunately, I don't have a Mac, I can't test on IOS

**Pull request closed without merging**
