### PR TITLE
Android jitsi update

### PR DESCRIPTION
**Pull request by Khodjaa**
Android jitsi update

### CODE REVIEW

**Comment by dancosta-fed** [comment]
Hi @Khodjaa, hope you're doing good! 

Firstly, thanks for this pull. 
I'm creating a small project just to test and try Jitisi with React Native, as I'm going to need to merge an application from Nativescript to RN. 

On the process, I've encounter some issues with running it on Android and perhaps you've came across something similar.
Well, let's start by saying that my iOS runs smoothly. 

On Android, however, I was facing some issues. Some of them I was able to fixing with patching your pull request, so thanks for that. But my main issue is the black screen on the first run.

I've seen some issues about it, and I've tried it all, but nothing seems to work for me. I thought patching your pull would solve it, but not yet. 

What happen is... every time I run the app on Android it returns a black screen. If i reload the application then, everything works fine. Have you, by any chance, faced something like that? And if so, how was your approach to fix it?

Thanks in advanced for your time...

here's my repo: https://github.com/dancosta-fed/jitsApp

**Comment by plannaAlain** [comment]
This is an important patch - can we get it merged asap.

**Comment by jvence** [comment]
Agreed. Can we get this fixed and merged? Thank you @Khodjaa and @skrafft

**Comment by skrafft** [comment]
I just bumped android to 5.1.0 and ios to 6.2.2

**Pull request closed without merging**
